AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Design Emotion Lambda functions
Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
    - dev
    - prod
    Description: Stage for deployment
  RedisHost:
    Type: String
    Default: crisp-moray-17911.upstash.io
    Description: Redis host
  RedisPort:
    Type: String
    Default: '6379'
    Description: Redis port
  SecretName:
    Type: String
    Default: openai-key
    Description: Name of the secret containing API keys
  AWSRegion:
    Type: String
    Default: eu-west-3
    Description: AWS Region
Conditions:
  IsDevelopment:
    Fn::Equals:
    - Ref: Stage
    - dev
Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Layers:
    - Ref: CommonDependenciesLayer
Metadata:
  AWS::ServerlessRepo::Application:
    Name: design-emotion
    Description: Design Emotion Lambda functions
    Author: Olivier
  AWS::SAM::Function:
    BuildMethod: python3.11
    Architectures:
    - x86_64
    Handler: app.lambda_handler
    Runtime: python3.11
    CodeUri: .
    AutoPublishAlias: live
    Environment:
      Variables:
        STAGE:
          Ref: Stage
        REDIS_HOST:
          Ref: RedisHost
        REDIS_PORT:
          Ref: RedisPort
        SECRET_NAME:
          Ref: SecretName
        AWS_REGION_DEPLOY:
          Ref: AWSRegion
Resources:
  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: design-emotion-dependencies
      Description: Common dependencies for Design Emotion functions
      ContentUri: s3://design-emotion-code/01c1dfd94ba0b5e0f222b5949f9a7b41
      CompatibleRuntimes:
      - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: false
      SamResourceId: CommonDependenciesLayer
  DesignTranscriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://design-emotion-code/c0fbf17ff85a703ba1a9c22d04da0e70
      Handler: design_transcript.lambda_handler_transcript
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          REDIS_HOST:
            Ref: RedisHost
          REDIS_PORT:
            Ref: RedisPort
          SECRET_NAME:
            Ref: SecretName
          AWS_REGION_DEPLOY:
            Ref: AWSRegion
      Description: Generates emotional transcript from website design
      PackageType: Zip
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR
        - Effect: Allow
          Action:
          - elasticache:DescribeCacheClusters
          - elasticache:DescribeReplicationGroups
          Resource: '*'
      Events:
        TranscriptApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DesignEmotionApi
            Path: /transcript
            Method: post
    Metadata:
      SamResourceId: DesignTranscriptFunction
  DesignTranscriptWithImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://design-emotion-code/c0fbf17ff85a703ba1a9c22d04da0e70
      Handler: design_transcript.lambda_handler_image_transcript
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          REDIS_HOST:
            Ref: RedisHost
          REDIS_PORT:
            Ref: RedisPort
          SECRET_NAME:
            Ref: SecretName
          AWS_REGION_DEPLOY:
            Ref: AWSRegion
      Description: Processes image uploads and generates transcript
      PackageType: Zip
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR
      Events:
        TranscriptWithImageApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DesignEmotionApi
            Path: /image-transcript
            Method: post
    Metadata:
      SamResourceId: DesignTranscriptWithImageFunction
  CacheInspectorFunction:
    Type: AWS::Serverless::Function
    Condition: IsDevelopment
    Properties:
      CodeUri: s3://design-emotion-code/c0fbf17ff85a703ba1a9c22d04da0e70
      Handler: design_transcript.lambda_handler_cache_get
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          REDIS_HOST:
            Ref: RedisHost
          REDIS_PORT:
            Ref: RedisPort
          SECRET_NAME:
            Ref: SecretName
          AWS_REGION_DEPLOY:
            Ref: AWSRegion
      Description: Inspect Redis cache (dev only)
      Events:
        CacheGetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DesignEmotionApi
            Path: /cache/get
            Method: get
    Metadata:
      SamResourceId: CacheInspectorFunction
  CacheClearFunction:
    Type: AWS::Serverless::Function
    Condition: IsDevelopment
    Properties:
      CodeUri: s3://design-emotion-code/c0fbf17ff85a703ba1a9c22d04da0e70
      Handler: design_transcript.lambda_handler_cache_clear
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          REDIS_HOST:
            Ref: RedisHost
          REDIS_PORT:
            Ref: RedisPort
          SECRET_NAME:
            Ref: SecretName
          AWS_REGION_DEPLOY:
            Ref: AWSRegion
      Description: Clears Redis cache (dev only)
      PackageType: Zip
      Events:
        CacheClearApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DesignEmotionApi
            Path: /cache/clear
            Method: delete
    Metadata:
      SamResourceId: CacheClearFunction
  DesignEmotionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: Stage
      Cors:
        AllowMethods: '''POST,GET,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for Design Emotion API
          Quota:
            Limit: 1000
            Period: MONTH
          Throttle:
            BurstLimit: 10
            RateLimit: 5
    Metadata:
      SamResourceId: DesignEmotionApi
Outputs:
  DesignEmotionApiEndpoint:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${DesignEmotionApi}.execute-api.${AWSRegion}.amazonaws.com/${Stage}/transcript
  DesignTranscriptFunctionArn:
    Description: ARN of DesignTranscriptFunction
    Value:
      Fn::GetAtt:
      - DesignTranscriptFunction
      - Arn
  DesignTranscriptWithImageFunctionArn:
    Description: ARN of DesignTranscriptWithImageFunction
    Value:
      Fn::GetAtt:
      - DesignTranscriptWithImageFunction
      - Arn
