version = 0.1
[default]
[default.build.parameters]
    cached = true
    parallel = true
    profile = "default"
    cache_basedir = ".aws-sam/build"
    skip_pull_image = false

[default.deploy.parameters]
    stack_name = "design-emotion-dev"
    s3_bucket = "design-emotion-code"
    s3_prefix = "design-emotion"
    region = "eu-west-3"
    confirm_changeset = true
    capabilities = "CAPABILITY_IAM"
    profile = "default"
    parameter_overrides = "Stage=dev"
    image_repositories = []

[prod.deploy.parameters]
    stack_name = "design-emotion-prod"
    s3_bucket = "design-emotion-code"
    s3_prefix = "design-emotion"
    region = "eu-west-3"
    confirm_changeset = true
    capabilities = "CAPABILITY_IAM"
    profile = "default"
    parameter_overrides = "Stage=prod"
    image_repositories = []

[default.local_start_api.parameters]
    warm_containers = "EAGER"

[local.invoke]
[local.invoke.parameters]
    profile = "default"
    parameter_overrides = "RedisHost=host.docker.internal RedisPort=6379 OpenAISecretArn=arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR"
    docker_network = "mynetwork"
    no_warm_containers = true

[local.start-api]
[local.start-api.parameters]
    profile = "default"
    parameter_overrides = "RedisHost=host.docker.internal RedisPort=6379 OpenAISecretArn=arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR"
    docker_network = "mynetwork"
    no_warm_containers = true