AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Design Emotion Lambda functions

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues: [dev, prod]
    Description: Stage for deployment
  RedisHost:
    Type: String
    Default: crisp-moray-17911.upstash.io
    Description: Redis host
  RedisPort:
    Type: String
    Default: "6379"
    Description: Redis port
  SecretName:
    Type: String
    Default: openai-key
    Description: Name of the secret containing API keys
  AWSRegion:
    Type: String
    Default: eu-west-3
    Description: AWS Region

Conditions:
  IsDevelopment: !Equals [ !Ref Stage, dev ]

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        STAGE: !Ref Stage
        REDIS_HOST: !Ref RedisHost
        REDIS_PORT: !Ref RedisPort
        SECRET_NAME: !Ref SecretName
        AWS_REGION: !Ref AWSRegion

Resources:
  DesignTranscriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: design_transcript.lambda_handler_transcript
      Description: Generates emotional transcript from website design
      PackageType: Zip
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action: [ secretsmanager:GetSecretValue ]
              Resource: arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR
            - Effect: Allow
              Action: [ elasticache:DescribeCacheClusters, elasticache:DescribeReplicationGroups ]
              Resource: "*"
      Events:
        TranscriptApi:
          Type: Api
          Properties:
            Path: /transcript
            Method: post

  DesignTranscriptWithImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: design_transcript.lambda_handler_image_transcript
      Description: Processes image uploads and generates transcript
      PackageType: Zip
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action: [ secretsmanager:GetSecretValue ]
              Resource: arn:aws:secretsmanager:eu-west-3:242201281082:secret:openai-key-6Bj9hR
      Events:
        TranscriptWithImageApi:
          Type: Api
          Properties:
            Path: /image-transcript
            Method: post

  CacheInspectorFunction:
    Type: AWS::Serverless::Function
    Condition: IsDevelopment
    Properties:
      CodeUri: .
      Handler: design_transcript.lambda_handler_cache_get
      Description: Inspect Redis cache (dev only)
      Events:
        CacheGetApi:
          Type: Api
          Properties:
            Path: /cache/get
            Method: get

  CacheClearFunction:
    Type: AWS::Serverless::Function
    Condition: IsDevelopment
    Properties:
      CodeUri: .
      Handler: design_transcript.lambda_handler_cache_clear
      Description: Clears Redis cache (dev only)
      PackageType: Zip
      Architectures:
        - x86_64
      Events:
        CacheClearApi:
          Type: Api
          Properties:
            Path: /cache/clear
            Method: delete

  DesignEmotionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "POST,GET,OPTIONS"
        AllowHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key"
        AllowOrigin: "*"
        MaxAge: 600
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for Design Emotion API
          Quota:
            Limit: 1000
            Period: MONTH
          Throttle:
            BurstLimit: 10
            RateLimit: 5

Outputs:
  DesignEmotionApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DesignEmotionApi}.execute-api.${AWSRegion}.amazonaws.com/${Stage}/transcript"
  DesignTranscriptFunctionArn:
    Description: "ARN of DesignTranscriptFunction"
    Value: !GetAtt DesignTranscriptFunction.Arn
  DesignTranscriptWithImageFunctionArn:
    Description: "ARN of DesignTranscriptWithImageFunction"
    Value: !GetAtt DesignTranscriptWithImageFunction.Arn

